### ISSUE TITLE
Change icon app and name

### ISSUE THREAD

**Issue by kubil-ismail** [suprayogo/Food-Recipe-Mobile#2]
![WhatsApp Image 2023-08-07 at 21 21 47](https://github.com/suprayogo/Food-Recipe-Android/assets/49361887/b66ef9b0-5c75-4698-b165-8a3143b11241)

**Comment by suprayogo** [comment]
![WhatsApp Image 2023-08-14 at 11 34 56](https://github.com/suprayogo/Food-Recipe-Mobile/assets/126061696/8faec584-d690-410e-9084-62980acb36fa)




it's been fixed
