### ISSUE TITLE
Fix Category icon in home

### ISSUE THREAD

**Issue by kubil-ismail** [suprayogo/Food-Recipe-Mobile#3]
Fix category icon if click show recipe by category in new page
![WhatsApp Image 2023-08-07 at 21 24 57](https://github.com/suprayogo/Food-Recipe-Android/assets/49361887/9940f769-7f44-4ef4-9c46-c20216963fe4)

**Comment by suprayogo** [comment]
![WhatsApp Image 2023-08-18 at 12 02 27](https://github.com/suprayogo/Food-Recipe-Mobile/assets/126061696/4be84152-cf6f-4d60-8038-e0f8da620f41)
![WhatsApp Image 2023-08-18 at 12 02 27a](https://github.com/suprayogo/Food-Recipe-Mobile/assets/126061696/16d71e09-be44-49a7-8f70-9412d3873d67)


i'm fixed
