### ISSUE TITLE
Create add recipe layout

### ISSUE THREAD

**Issue by kubil-ismail** [suprayogo/Food-Recipe-Mobile#4]
![WhatsApp Image 2023-08-07 at 21 24 58](https://github.com/suprayogo/Food-Recipe-Android/assets/49361887/ec267f2e-0330-4850-9801-16ac527759d3)

**Comment by suprayogo** [comment]
![Uploading WhatsApp Image 2023-08-14 at 11.36.28.jpg…]()


it's been fixed

**Comment by suprayogo** [comment]
![WhatsApp Image 2023-08-14 at 11 36 28](https://github.com/suprayogo/Food-Recipe-Mobile/assets/126061696/8fd51f36-eb4d-44d3-81ec-1e213a577f7e)


it's been fixed
