### ISSUE TITLE
Stuck in loading indicator register

### ISSUE THREAD

**Issue by kubil-ismail** [suprayogo/Food-Recipe-Mobile#6]
![WhatsApp Image 2023-08-07 at 21 29 50](https://github.com/suprayogo/Food-Recipe-Android/assets/49361887/7556e0a5-c648-4a5e-a3a9-1d24d4b2abed)

**Comment by suprayogo** [comment]
![WhatsApp Image 2023-08-09 at 09 40 36](https://github.com/suprayogo/Food-Recipe-Mobile/assets/126061696/6e7137d3-8444-4ec4-8c1f-d0ac05fe052c)


Previously, it had not displayed an error message for email notifications that had been registered, so loading occurred periodically. i've fixed it
